language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g grunt-cli

script: grunt

deploy:
  provider: releases
  api-key: "NtnyLotYQlma7LoE/veolFMdbdfT6R1jnBLJFhrJELTWq0GLCqrakWfwtP3UTyBLHdDkCqFtboG5Zr0RyJ4o5vTHiVeJn2bifxZyYIablUIWIQO8g8MYklz96vmRAru68YhfXp8nQ0xjZjngs5Y0KoiPdt4Jj6oCeO2jpPFtiRk="
  file: "package/Hex-Clock.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
